# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 490)
        MainWindow.setMinimumSize(QtCore.QSize(1022, 490))
        MainWindow.setMaximumSize(QtCore.QSize(1022, 490))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidgetMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetMain.setGeometry(QtCore.QRect(170, 0, 851, 471))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        self.tabWidgetMain.setFont(font)
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 231, 411))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/kyber.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(330, 180, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(600, 370, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.tabWidgetMain.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pBtnFileDownload = QtWidgets.QPushButton(self.tab)
        self.pBtnFileDownload.setGeometry(QtCore.QRect(340, 330, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(10)
        self.pBtnFileDownload.setFont(font)
        self.pBtnFileDownload.setObjectName("pBtnFileDownload")
        self.lEdtFileDownloadLink = QtWidgets.QLineEdit(self.tab)
        self.lEdtFileDownloadLink.setGeometry(QtCore.QRect(140, 60, 551, 41))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(11)
        self.lEdtFileDownloadLink.setFont(font)
        self.lEdtFileDownloadLink.setObjectName("lEdtFileDownloadLink")
        self.lEdtFileDownloadLocation = QtWidgets.QLineEdit(self.tab)
        self.lEdtFileDownloadLocation.setGeometry(QtCore.QRect(140, 140, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(11)
        self.lEdtFileDownloadLocation.setFont(font)
        self.lEdtFileDownloadLocation.setObjectName("lEdtFileDownloadLocation")
        self.pBtnFileSaveLocation = QtWidgets.QPushButton(self.tab)
        self.pBtnFileSaveLocation.setGeometry(QtCore.QRect(640, 140, 51, 41))
        self.pBtnFileSaveLocation.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtnFileSaveLocation.setIcon(icon)
        self.pBtnFileSaveLocation.setIconSize(QtCore.QSize(30, 30))
        self.pBtnFileSaveLocation.setObjectName("pBtnFileSaveLocation")
        self.pBarFileDownload = QtWidgets.QProgressBar(self.tab)
        self.pBarFileDownload.setGeometry(QtCore.QRect(140, 240, 601, 23))
        self.pBarFileDownload.setProperty("value", 0)
        self.pBarFileDownload.setObjectName("pBarFileDownload")
        self.tabWidgetMain.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 851, 441))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lEdtVideoUrl = QtWidgets.QLineEdit(self.tab_3)
        self.lEdtVideoUrl.setGeometry(QtCore.QRect(140, 30, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(11)
        self.lEdtVideoUrl.setFont(font)
        self.lEdtVideoUrl.setObjectName("lEdtVideoUrl")
        self.lEdtVideoDownloadLocation = QtWidgets.QLineEdit(self.tab_3)
        self.lEdtVideoDownloadLocation.setGeometry(QtCore.QRect(140, 100, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(11)
        self.lEdtVideoDownloadLocation.setFont(font)
        self.lEdtVideoDownloadLocation.setObjectName("lEdtVideoDownloadLocation")
        self.pBtnVideoSaveLocation = QtWidgets.QPushButton(self.tab_3)
        self.pBtnVideoSaveLocation.setGeometry(QtCore.QRect(640, 100, 51, 41))
        self.pBtnVideoSaveLocation.setText("")
        self.pBtnVideoSaveLocation.setIcon(icon)
        self.pBtnVideoSaveLocation.setIconSize(QtCore.QSize(30, 30))
        self.pBtnVideoSaveLocation.setObjectName("pBtnVideoSaveLocation")
        self.pBarVideoDownload = QtWidgets.QProgressBar(self.tab_3)
        self.pBarVideoDownload.setGeometry(QtCore.QRect(140, 240, 601, 23))
        self.pBarVideoDownload.setProperty("value", 0)
        self.pBarVideoDownload.setObjectName("pBarVideoDownload")
        self.pBtnVideoDownload = QtWidgets.QPushButton(self.tab_3)
        self.pBtnVideoDownload.setGeometry(QtCore.QRect(320, 320, 211, 28))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(9)
        self.pBtnVideoDownload.setFont(font)
        self.pBtnVideoDownload.setObjectName("pBtnVideoDownload")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(240, 180, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cBoxVideoQuality = QtWidgets.QComboBox(self.tab_3)
        self.cBoxVideoQuality.setGeometry(QtCore.QRect(350, 180, 201, 22))
        self.cBoxVideoQuality.setObjectName("cBoxVideoQuality")
        self.pBtnVideoData = QtWidgets.QPushButton(self.tab_3)
        self.pBtnVideoData.setGeometry(QtCore.QRect(640, 30, 51, 41))
        self.pBtnVideoData.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtnVideoData.setIcon(icon1)
        self.pBtnVideoData.setIconSize(QtCore.QSize(25, 25))
        self.pBtnVideoData.setObjectName("pBtnVideoData")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lEdtPlaylistDownloadLocation = QtWidgets.QLineEdit(self.tab_4)
        self.lEdtPlaylistDownloadLocation.setGeometry(QtCore.QRect(150, 100, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(11)
        self.lEdtPlaylistDownloadLocation.setFont(font)
        self.lEdtPlaylistDownloadLocation.setObjectName("lEdtPlaylistDownloadLocation")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(310, 180, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lEdtPlaylistUrl = QtWidgets.QLineEdit(self.tab_4)
        self.lEdtPlaylistUrl.setGeometry(QtCore.QRect(150, 30, 551, 41))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(11)
        self.lEdtPlaylistUrl.setFont(font)
        self.lEdtPlaylistUrl.setObjectName("lEdtPlaylistUrl")
        self.cBoxPlaylistVideoQuality = QtWidgets.QComboBox(self.tab_4)
        self.cBoxPlaylistVideoQuality.setGeometry(QtCore.QRect(420, 180, 81, 22))
        self.cBoxPlaylistVideoQuality.setObjectName("cBoxPlaylistVideoQuality")
        self.cBoxPlaylistVideoQuality.addItem("")
        self.cBoxPlaylistVideoQuality.addItem("")
        self.pBarPlaylistDownload = QtWidgets.QProgressBar(self.tab_4)
        self.pBarPlaylistDownload.setGeometry(QtCore.QRect(140, 280, 601, 23))
        self.pBarPlaylistDownload.setProperty("value", 0)
        self.pBarPlaylistDownload.setObjectName("pBarPlaylistDownload")
        self.pBtnPlaylistSaveLocation = QtWidgets.QPushButton(self.tab_4)
        self.pBtnPlaylistSaveLocation.setGeometry(QtCore.QRect(650, 100, 51, 41))
        self.pBtnPlaylistSaveLocation.setText("")
        self.pBtnPlaylistSaveLocation.setIcon(icon)
        self.pBtnPlaylistSaveLocation.setIconSize(QtCore.QSize(30, 30))
        self.pBtnPlaylistSaveLocation.setObjectName("pBtnPlaylistSaveLocation")
        self.pBtnPlaylistDownload = QtWidgets.QPushButton(self.tab_4)
        self.pBtnPlaylistDownload.setGeometry(QtCore.QRect(310, 340, 211, 28))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(9)
        self.pBtnPlaylistDownload.setFont(font)
        self.pBtnPlaylistDownload.setObjectName("pBtnPlaylistDownload")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(190, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(430, 220, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Nunito SemiBold")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lblCurrentVideoNumber = QtWidgets.QLabel(self.tab_4)
        self.lblCurrentVideoNumber.setGeometry(QtCore.QRect(300, 210, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblCurrentVideoNumber.setFont(font)
        self.lblCurrentVideoNumber.setText("")
        self.lblCurrentVideoNumber.setObjectName("lblCurrentVideoNumber")
        self.lblTotalVideoCount = QtWidgets.QLabel(self.tab_4)
        self.lblTotalVideoCount.setGeometry(QtCore.QRect(600, 210, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblTotalVideoCount.setFont(font)
        self.lblTotalVideoCount.setText("")
        self.lblTotalVideoCount.setObjectName("lblTotalVideoCount")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidgetMain.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pBtnQDarkTheme = QtWidgets.QPushButton(self.tab_6)
        self.pBtnQDarkTheme.setGeometry(QtCore.QRect(230, 220, 171, 121))
        self.pBtnQDarkTheme.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.pBtnQDarkTheme.setText("")
        self.pBtnQDarkTheme.setObjectName("pBtnQDarkTheme")
        self.pBtnQDarkGrayTheme = QtWidgets.QPushButton(self.tab_6)
        self.pBtnQDarkGrayTheme.setGeometry(QtCore.QRect(440, 220, 171, 121))
        self.pBtnQDarkGrayTheme.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.pBtnQDarkGrayTheme.setText("")
        self.pBtnQDarkGrayTheme.setObjectName("pBtnQDarkGrayTheme")
        self.pBtnDarkBlueTheme = QtWidgets.QPushButton(self.tab_6)
        self.pBtnDarkBlueTheme.setGeometry(QtCore.QRect(650, 220, 171, 121))
        self.pBtnDarkBlueTheme.setStyleSheet("background-color: rgb(48, 47, 47);")
        self.pBtnDarkBlueTheme.setText("")
        self.pBtnDarkBlueTheme.setObjectName("pBtnDarkBlueTheme")
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(230, 80, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pBtnDefaultTheme = QtWidgets.QPushButton(self.tab_6)
        self.pBtnDefaultTheme.setGeometry(QtCore.QRect(20, 220, 171, 121))
        self.pBtnDefaultTheme.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pBtnDefaultTheme.setText("")
        self.pBtnDefaultTheme.setObjectName("pBtnDefaultTheme")
        self.tabWidgetMain.addTab(self.tab_6, "")
        self.pBtnHomeTab = QtWidgets.QPushButton(self.centralwidget)
        self.pBtnHomeTab.setGeometry(QtCore.QRect(20, 20, 131, 101))
        self.pBtnHomeTab.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtnHomeTab.setIcon(icon2)
        self.pBtnHomeTab.setIconSize(QtCore.QSize(60, 60))
        self.pBtnHomeTab.setObjectName("pBtnHomeTab")
        self.pBtnFileDownloadTab = QtWidgets.QPushButton(self.centralwidget)
        self.pBtnFileDownloadTab.setGeometry(QtCore.QRect(20, 130, 131, 101))
        self.pBtnFileDownloadTab.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtnFileDownloadTab.setIcon(icon3)
        self.pBtnFileDownloadTab.setIconSize(QtCore.QSize(60, 60))
        self.pBtnFileDownloadTab.setObjectName("pBtnFileDownloadTab")
        self.pBtnVideoDownloadTab = QtWidgets.QPushButton(self.centralwidget)
        self.pBtnVideoDownloadTab.setGeometry(QtCore.QRect(20, 240, 131, 101))
        self.pBtnVideoDownloadTab.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/youtube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtnVideoDownloadTab.setIcon(icon4)
        self.pBtnVideoDownloadTab.setIconSize(QtCore.QSize(60, 60))
        self.pBtnVideoDownloadTab.setObjectName("pBtnVideoDownloadTab")
        self.pBtnSettingsTab = QtWidgets.QPushButton(self.centralwidget)
        self.pBtnSettingsTab.setGeometry(QtCore.QRect(20, 350, 131, 101))
        self.pBtnSettingsTab.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtnSettingsTab.setIcon(icon5)
        self.pBtnSettingsTab.setIconSize(QtCore.QSize(60, 60))
        self.pBtnSettingsTab.setObjectName("pBtnSettingsTab")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetMain.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kyber Download Manager"))
        self.label_7.setText(_translate("MainWindow", "Download files, youtube videos and playlists"))
        self.label_8.setText(_translate("MainWindow", "Made by: Subhajit Nandi Github repo <a href=\"https://github.com/Kristency/kyber-download-manager\">here</a>"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.pBtnFileDownload.setText(_translate("MainWindow", "Download"))
        self.lEdtFileDownloadLink.setPlaceholderText(_translate("MainWindow", "Enter download link here"))
        self.lEdtFileDownloadLocation.setPlaceholderText(_translate("MainWindow", "Use browse button to enter save location"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.lEdtVideoUrl.setPlaceholderText(_translate("MainWindow", "Enter video URL"))
        self.lEdtVideoDownloadLocation.setPlaceholderText(_translate("MainWindow", "Use browse button to enter save location"))
        self.pBtnVideoDownload.setText(_translate("MainWindow", "Start Download"))
        self.label.setText(_translate("MainWindow", "Video Quality"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "One Video"))
        self.lEdtPlaylistDownloadLocation.setPlaceholderText(_translate("MainWindow", "Use browse button to enter save location"))
        self.label_2.setText(_translate("MainWindow", "Video Quality"))
        self.lEdtPlaylistUrl.setPlaceholderText(_translate("MainWindow", "Enter Playlist URL"))
        self.cBoxPlaylistVideoQuality.setItemText(0, _translate("MainWindow", "low"))
        self.cBoxPlaylistVideoQuality.setItemText(1, _translate("MainWindow", "high"))
        self.pBtnPlaylistDownload.setText(_translate("MainWindow", "Start Download"))
        self.label_3.setText(_translate("MainWindow", "Current Video : "))
        self.label_4.setText(_translate("MainWindow", "Total Videos in Playlist : "))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Full Playlist"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_5.setText(_translate("MainWindow", "Choose Your Theme"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_6), _translate("MainWindow", "Page"))
import photos_rc
